### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by dandoh**

### CODE REVIEW

**Comment by dandoh** [comment]
Just found out stylish-haskell and hindent don't agree with how to format imports. 
Stylish-haskell actually does do much, so I think just hident is good enough. Besides, we dont want to go through two steps just to format. What do you think?

**Comment by CSchank** [comment]
Keeping it simple is probably a good idea yes. Sounds good to me.

**Comment by dandoh** [comment]
Ok, so I will send another PR for files with only `hindent` formated but not `stylish-haskell`

**Comment by CSchank** [comment]
Oh, sorry if merged this prematurely.

**Pull request merged**
