### PR TITLE
Prettify tweak

### PR DESCRIPTION
**Pull request by CSchank**
Small tweak to prettify that will not put an extra space if there is no dimension to show. This is a very small fix; I only made this a PR in the off-chance that something will break if we remove this space. I'm guessing not, that prettify is "human-readable only" and it doesn't matter much. Just confirming.

### CODE REVIEW

**Comment by CSchank** [comment]
Should this be merged into another branch before `master`? A dev branch? Sorry.

**Comment by dandoh** [comment]
Why there are so many changes in this PR?

**Comment by CSchank** [comment]
I am not sure!! When I made it it had like two changes in only the Prettify.hs file. Maybe because other things have been changed in the target branch?

**Comment by dandoh** [comment]
Then probably we should cherry-pick those in Prettify.hs only and create a new PR 🤔

**Pull request closed without merging**
